name: Testbed

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build macOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-26-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Qt6
        run: |
          brew install qt@6
          echo "$(brew --prefix qt@6)/bin" >> $GITHUB_PATH
      - name: Build 
        run: |
          qmake
          make -j$(sysctl -n hw.ncpu)
      - name: Tarball
        run: |
          mkdir -p package/usr/local/bin
          mkdir -p package/usr/local/etc/skyscraper
          mkdir -p package/usr/local/etc/skyscraper/cache
          mkdir -p package/usr/local/etc/skyscraper/import
          mkdir -p package/usr/local/etc/skyscraper/resources
          cp Skyscraper.app/Contents/MacOS/Skyscraper package/usr/local/bin/
          cd package
          tar -czf ../skyscraper-${{ needs.create-release.outputs.version }}-macos-$(uname -m).tar.gz *
          cd ..
      - name: Smoketest
        run: bash ./Skyscraper.app/Contents/MacOS/Skyscraper --buildinfo && ./Skyscraper.app/Contents/MacOS/Skyscraper --configinfo
      
        
